title: Daddy Mosanda # your name (or website title) here
logo: "/images/daddy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer | Sys Admin ( Automtion ) | Database Management | Amazon Web Service Cloud Practitioner loading...

  <br><br>
  
  Kinshasa, Democratic Republic of Congo 
  <br>
  
  <br>
  Master of Engineering in Computer Technology, Beijing Jiaotong University. 
  Barchelor of Computer Application, Bangalore University
  <br><br>
  <a href="https://www.linkedin.com/in/daddy-mosanda-66678574">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
